language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install pytest --upgrade
  - pip install boto
script:
  - make test lint
