language: python
cache: pip
python:
  - "3.6"
before_install:
  - sudo rm -f /etc/boto.cfg
  - mkdir -p ~/.aws
  - touch ~/.aws/credentials
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install pytest --upgrade
  - pip install awscli
script:
  - make setupaws
  - make test lint
  - sonar-scanner
addons:
  sonarcloud:
    organization: "johnnyiller-github" # the key of the org you chose at step #3
    token:
      secure: "QoBtWBtW7oDGBNvWA+8xVuSioUfYWTM2Vd8tO7F9zeEI2ssIBy8QgqY7K4YLE5MTlDNoJ2C6CKRteIbreDYbVHQBCpIrgodeGYXs6JpKVLZzWNZzg2apXVi7sMwg2H0SDOfybkk9fsgRCcnTnydO0FW51Cp+jKj1KzVKf9WPbos+OMUSIbhK4t0EDjkbkznf7+7ljs1Mf7UjmDifBkGVQ1emF54igjQ51zxiTUjD02ijV//F1IAC70SXN5GzvyXH4NPNJJ9vVys0dbbeI8nym48sEkyUzRldqiSSFVLM7Y9XV4u5WlBUXKx39szLrF5KfMkuQQ9k4tWI92q9WCV/Po6Dg7ampeje0VTeJrTavjKm/10RlWedObl98odjbOQWiG5ZqLrRD75T/CrEflWfSqRfU8iF62gGwTQpuKPg3FjtCVPplYpt/IKM3zuEXiLqcTh0NM71IpM3Z1/5Q2yCbPYSA81LxP94IUS94X4L5hdhEKR3o0ufIMisrKL0sBZjHa+A6KVPzzpkQRkDG8it4QkNtNnD19GOiReVqKRU8HVfxPb31mOTSSMOYuis3WUx/fFrf56AA5omGJyTdsWxt7RJe+Dkb4XmsXd6OpNwEHzZfy1+zoSl0EEww43jTBj31d2wD0nvyKUYn0cQPiftOHo9mhyMVOi4No1h1kVsZ6w="
