language: python
cache: pip
python:
  - "3.6"
before_install:
  - sudo rm -f /etc/boto.cfg
  - mkdir -p ~/.aws
  - touch ~/.aws/credentials
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install pytest --upgrade
  - pip install awscli
script:
  - make setupaws
  - make test lint
