language: python
cache: pip
python:
  - "3.6"
before_install:
  - sudo rm -f /etc/boto.cfg
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install pytest boto --upgrade
script:
  - make test lint
